### ISSUE TITLE
Checks for identy element also mandatory for Ristretto255

### ISSUE THREAD

**Issue by BjoernMHaase** [codahale/cpace#4]
Hello Codahale,

just noticed your remark in the readme. I just wanted to point you to the fact that checking for the identity element is strictly necessary also for Ristretto255.

In the latest version of the Internet Draft, we have provided explicit test vectors for implementers whishing to use ristretto or decaf.

https://datatracker.ietf.org/doc/draft-irtf-cfrg-cpace/

**Comment by codahale** [comment]
Thanks for the heads up!
